// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/googleinterns/knative-continuous-delivery/pkg/apis/delivery/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePolicyStates implements PolicyStateInterface
type FakePolicyStates struct {
	Fake *FakeDeliveryV1alpha1
	ns   string
}

var policystatesResource = schema.GroupVersionResource{Group: "delivery.knative.dev", Version: "v1alpha1", Resource: "policystates"}

var policystatesKind = schema.GroupVersionKind{Group: "delivery.knative.dev", Version: "v1alpha1", Kind: "PolicyState"}

// Get takes name of the policyState, and returns the corresponding policyState object, and an error if there is any.
func (c *FakePolicyStates) Get(name string, options v1.GetOptions) (result *v1alpha1.PolicyState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(policystatesResource, c.ns, name), &v1alpha1.PolicyState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolicyState), err
}

// List takes label and field selectors, and returns the list of PolicyStates that match those selectors.
func (c *FakePolicyStates) List(opts v1.ListOptions) (result *v1alpha1.PolicyStateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(policystatesResource, policystatesKind, c.ns, opts), &v1alpha1.PolicyStateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PolicyStateList{ListMeta: obj.(*v1alpha1.PolicyStateList).ListMeta}
	for _, item := range obj.(*v1alpha1.PolicyStateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested policyStates.
func (c *FakePolicyStates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(policystatesResource, c.ns, opts))

}

// Create takes the representation of a policyState and creates it.  Returns the server's representation of the policyState, and an error, if there is any.
func (c *FakePolicyStates) Create(policyState *v1alpha1.PolicyState) (result *v1alpha1.PolicyState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(policystatesResource, c.ns, policyState), &v1alpha1.PolicyState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolicyState), err
}

// Update takes the representation of a policyState and updates it. Returns the server's representation of the policyState, and an error, if there is any.
func (c *FakePolicyStates) Update(policyState *v1alpha1.PolicyState) (result *v1alpha1.PolicyState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(policystatesResource, c.ns, policyState), &v1alpha1.PolicyState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolicyState), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePolicyStates) UpdateStatus(policyState *v1alpha1.PolicyState) (*v1alpha1.PolicyState, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(policystatesResource, "status", c.ns, policyState), &v1alpha1.PolicyState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolicyState), err
}

// Delete takes name of the policyState and deletes it. Returns an error if one occurs.
func (c *FakePolicyStates) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(policystatesResource, c.ns, name), &v1alpha1.PolicyState{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePolicyStates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(policystatesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PolicyStateList{})
	return err
}

// Patch applies the patch and returns the patched policyState.
func (c *FakePolicyStates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PolicyState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(policystatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.PolicyState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolicyState), err
}
