// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/googleinterns/knative-continuous-delivery/pkg/apis/delivery/v1alpha1"
	scheme "github.com/googleinterns/knative-continuous-delivery/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PolicyStatesGetter has a method to return a PolicyStateInterface.
// A group's client should implement this interface.
type PolicyStatesGetter interface {
	PolicyStates(namespace string) PolicyStateInterface
}

// PolicyStateInterface has methods to work with PolicyState resources.
type PolicyStateInterface interface {
	Create(*v1alpha1.PolicyState) (*v1alpha1.PolicyState, error)
	Update(*v1alpha1.PolicyState) (*v1alpha1.PolicyState, error)
	UpdateStatus(*v1alpha1.PolicyState) (*v1alpha1.PolicyState, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PolicyState, error)
	List(opts v1.ListOptions) (*v1alpha1.PolicyStateList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PolicyState, err error)
	PolicyStateExpansion
}

// policyStates implements PolicyStateInterface
type policyStates struct {
	client rest.Interface
	ns     string
}

// newPolicyStates returns a PolicyStates
func newPolicyStates(c *DeliveryV1alpha1Client, namespace string) *policyStates {
	return &policyStates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the policyState, and returns the corresponding policyState object, and an error if there is any.
func (c *policyStates) Get(name string, options v1.GetOptions) (result *v1alpha1.PolicyState, err error) {
	result = &v1alpha1.PolicyState{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("policystates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PolicyStates that match those selectors.
func (c *policyStates) List(opts v1.ListOptions) (result *v1alpha1.PolicyStateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PolicyStateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("policystates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested policyStates.
func (c *policyStates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("policystates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a policyState and creates it.  Returns the server's representation of the policyState, and an error, if there is any.
func (c *policyStates) Create(policyState *v1alpha1.PolicyState) (result *v1alpha1.PolicyState, err error) {
	result = &v1alpha1.PolicyState{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("policystates").
		Body(policyState).
		Do().
		Into(result)
	return
}

// Update takes the representation of a policyState and updates it. Returns the server's representation of the policyState, and an error, if there is any.
func (c *policyStates) Update(policyState *v1alpha1.PolicyState) (result *v1alpha1.PolicyState, err error) {
	result = &v1alpha1.PolicyState{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("policystates").
		Name(policyState.Name).
		Body(policyState).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *policyStates) UpdateStatus(policyState *v1alpha1.PolicyState) (result *v1alpha1.PolicyState, err error) {
	result = &v1alpha1.PolicyState{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("policystates").
		Name(policyState.Name).
		SubResource("status").
		Body(policyState).
		Do().
		Into(result)
	return
}

// Delete takes name of the policyState and deletes it. Returns an error if one occurs.
func (c *policyStates) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("policystates").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *policyStates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("policystates").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched policyState.
func (c *policyStates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PolicyState, err error) {
	result = &v1alpha1.PolicyState{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("policystates").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
