// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package defaults

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousDeploymentRoute) DeepCopyInto(out *ContinuousDeploymentRoute) {
	*out = *in
	in.Route.DeepCopyInto(&out.Route)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousDeploymentRoute.
func (in *ContinuousDeploymentRoute) DeepCopy() *ContinuousDeploymentRoute {
	if in == nil {
		return nil
	}
	out := new(ContinuousDeploymentRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContinuousDeploymentRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
