// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	deliveryv1alpha1 "github.com/googleinterns/knative-continuous-delivery/pkg/apis/delivery/v1alpha1"
	versioned "github.com/googleinterns/knative-continuous-delivery/pkg/client/clientset/versioned"
	internalinterfaces "github.com/googleinterns/knative-continuous-delivery/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/googleinterns/knative-continuous-delivery/pkg/client/listers/delivery/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PolicyStateInformer provides access to a shared informer and lister for
// PolicyStates.
type PolicyStateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PolicyStateLister
}

type policyStateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPolicyStateInformer constructs a new informer for PolicyState type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPolicyStateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPolicyStateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPolicyStateInformer constructs a new informer for PolicyState type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPolicyStateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeliveryV1alpha1().PolicyStates(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeliveryV1alpha1().PolicyStates(namespace).Watch(options)
			},
		},
		&deliveryv1alpha1.PolicyState{},
		resyncPeriod,
		indexers,
	)
}

func (f *policyStateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPolicyStateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *policyStateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&deliveryv1alpha1.PolicyState{}, f.defaultInformer)
}

func (f *policyStateInformer) Lister() v1alpha1.PolicyStateLister {
	return v1alpha1.NewPolicyStateLister(f.Informer().GetIndexer())
}
